### ISSUE TITLE
[Issue] Admin Model & API

### ISSUE THREAD

**Issue by JongbeomLee623** [LINE-NOW/LINENOW-Server#6]
## 🛠 Issue

관리자 관련 모델 및 API 개발 

## 📝 To-do

- [x] 관리자 모델 설계
- [x] 관리자용 예약관리 API [취소, 호출, 착석 등]
- [x] 관리자용 예약 상태 호출 API
- [ ] 부스 상태관리
- [x] FAQ
- [ ] 등등등 추가 예정
