### ISSUE TITLE
[Feature] User - Waiting API

### ISSUE THREAD

**Issue by dudtlstm** [LINE-NOW/LINENOW-Server#7]
## 🛠 Issue
사용자 측 웨이팅 관련 API를 설계합니다.

## 📝 To-do
- [x] 웨이팅 모델 설계
- [x] 부스 전체 대기 팀 수 조회 API(부스쪽에 추가)
- [x] 나의 대기 리스트 API
- [x] 나의 대기 상세 API
- [x] 대기 등록 API
- [x] 대기 취소하기 API
- [x] 입장 확정 API
- [x] 시간 초과 / 직접 취소 구분하기
